-- Insert Iranian Banks
-- Major banks in Iran for contractor banking information
-- Actual schema: ID, BANK_CODE (10 chars), BANK_NAME (100 chars), IS_ACTIVE, CREATED_DATE

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (1, 'BMI', 'بانک ملی ایران', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (2, 'SEPAH', 'بانک سپه', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (3, 'TEJARAT', 'بانک تجارت', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (4, 'SADERAT', 'بانک صادرات ایران', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (5, 'MELLAT', 'بانک ملت', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (6, 'REFAH', 'بانک رفاه کارگران', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (7, 'MASKAN', 'بانک مسکن', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (8, 'POST', 'پست بانک ایران', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (9, 'TOSEE', 'بانک توسعه تعاون', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (10, 'KESHAVARZI', 'بانک کشاورزی', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (11, 'SANAT', 'بانک صنعت و معدن', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (12, 'PARSIAN', 'بانک پارسیان', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (13, 'PASARGAD', 'بانک پاسارگاد', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (14, 'KARAFARIN', 'بانک کارآفرین', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (15, 'SAMAN', 'بانک سامان', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (16, 'SARMAYEH', 'بانک سرمایه', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (17, 'SINA', 'بانک سینا', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (18, 'SHAHR', 'بانک شهر', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (19, 'DAY', 'بانک دی', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (20, 'EGHTESAD', 'بانک اقتصاد نوین', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (21, 'AYANDEH', 'بانک آینده', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (22, 'ANSAR', 'بانک انصار', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (23, 'GARDESHGAR', 'بانک گردشگری', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (24, 'HEKMAT', 'بانک حکمت ایرانیان', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (25, 'RESALAT', 'بانک قرض‌الحسنه رسالت', 1, SYSDATE);

INSERT INTO BASE_BANK (ID, BANK_CODE, BANK_NAME, IS_ACTIVE, CREATED_DATE)
VALUES (26, 'MEHR', 'بانک قرض‌الحسنه مهر ایران', 1, SYSDATE);

COMMIT;
