-- Insert Contractor Types
-- Common contractor types in Iranian tender system
-- Schema: ID, TYPE_CODE (20), TYPE_NAME (100), DESCRIPTION (500), IS_ACTIVE, CREATED_DATE

INSERT INTO BASE_CONTRACTOR_TYPE (ID, TYPE_CODE, TYPE_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (1, 'PRIVATE', 'خصوصی', 'شرکت خصوصی', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_TYPE (ID, TYPE_CODE, TYPE_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (2, 'PUBLIC', 'دولتی', 'شرکت دولتی', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_TYPE (ID, TYPE_CODE, TYPE_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (3, 'SEMI-PUBLIC', 'نیمه دولتی', 'شرکت نیمه دولتی', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_TYPE (ID, TYPE_CODE, TYPE_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (4, 'COOPERATIVE', 'تعاونی', 'شرکت تعاونی', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_TYPE (ID, TYPE_CODE, TYPE_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (5, 'LIMITED', 'سهامی خاص', 'شرکت سهامی خاص', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_TYPE (ID, TYPE_CODE, TYPE_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (6, 'PUBLIC-LIMITED', 'سهامی عام', 'شرکت سهامی عام', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_TYPE (ID, TYPE_CODE, TYPE_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (7, 'LLC', 'با مسئولیت محدود', 'شرکت با مسئولیت محدود', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_TYPE (ID, TYPE_CODE, TYPE_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (8, 'PARTNERSHIP', 'تضامنی', 'شرکت تضامنی', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_TYPE (ID, TYPE_CODE, TYPE_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (9, 'CONSORTIUM', 'کنسرسیوم', 'اتحادیه شرکت‌ها (کنسرسیوم)', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_TYPE (ID, TYPE_CODE, TYPE_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (10, 'INDIVIDUAL', 'شخص حقیقی', 'پیمانکار شخص حقیقی', 1, SYSDATE);

COMMIT;
