-- Insert Contractor Activities
-- BASE_CONTRACTOR_ACTIVITY table: ID, ACTIVITY_CODE (20 chars), ACTIVITY_NAME (200 chars), DESCRIPTION, IS_ACTIVE, CREATED_DATE
-- Activities that contractors can perform

-- Construction Activities
INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (1, 'BUILD-RES', 'ساختمان مسکونی', 'احداث و بازسازی ساختمان‌های مسکونی', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (2, 'BUILD-COM', 'ساختمان تجاری', 'احداث ساختمان‌های تجاری و اداری', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (3, 'BUILD-IND', 'ساختمان صنعتی', 'احداث سوله و ساختمان‌های صنعتی', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (4, 'BUILD-HIGH', 'ساختمان بلند', 'احداث ساختمان‌های بلند مرتبه', 1, SYSDATE);

-- Road Construction Activities
INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (5, 'ROAD-HIGHWAY', 'بزرگراه و آزادراه', 'احداث و نگهداری بزرگراه و آزادراه', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (6, 'ROAD-URBAN', 'راه شهری', 'راه‌سازی شهری و معابر', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (7, 'ROAD-RURAL', 'راه روستایی', 'راه‌سازی روستایی و عشایری', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (8, 'ROAD-BRIDGE', 'پل و تونل', 'احداث و مرمت پل و تونل', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (9, 'ROAD-ASPHALT', 'آسفالت', 'آسفالت و روکش راه', 1, SYSDATE);

-- Water & Wastewater Activities
INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (10, 'WATER-SUPPLY', 'شبکه آب', 'احداث شبکه تامین و توزیع آب', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (11, 'WATER-SEWER', 'شبکه فاضلاب', 'احداث شبکه جمع‌آوری فاضلاب', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (12, 'WATER-TREAT', 'تصفیه‌خانه', 'احداث تصفیه‌خانه آب و فاضلاب', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (13, 'WATER-DAM', 'سد و مخزن', 'احداث سد و مخازن ذخیره آب', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (14, 'WATER-PUMP', 'ایستگاه پمپاژ', 'احداث ایستگاه‌های پمپاژ آب', 1, SYSDATE);

-- Power & Energy Activities
INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (15, 'POWER-PLANT', 'نیروگاه', 'احداث نیروگاه و تولید برق', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (16, 'POWER-TRANS', 'انتقال برق', 'احداث شبکه انتقال برق', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (17, 'POWER-DIST', 'توزیع برق', 'احداث شبکه توزیع برق', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (18, 'POWER-SOLAR', 'انرژی خورشیدی', 'نصب و راه‌اندازی سیستم خورشیدی', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (19, 'POWER-WIND', 'انرژی بادی', 'احداث نیروگاه بادی', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (20, 'POWER-LIGHT', 'روشنایی شهری', 'احداث سیستم روشنایی معابر', 1, SYSDATE);

-- Mechanical Activities
INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (21, 'MECH-HVAC', 'سرمایش و گرمایش', 'نصب سیستم‌های HVAC', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (22, 'MECH-PLUMB', 'لوله‌کشی', 'لوله‌کشی و تاسیسات بهداشتی', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (23, 'MECH-ELEV', 'آسانسور و پله برقی', 'نصب و نگهداری آسانسور و پله برقی', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (24, 'MECH-FIRE', 'اطفاء حریق', 'نصب سیستم‌های اطفاء حریق', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (25, 'MECH-GAS', 'گاز رسانی', 'نصب شبکه گاز رسانی', 1, SYSDATE);

-- Industrial Activities
INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (26, 'IND-OIL', 'نفت و گاز', 'پروژه‌های صنایع نفت و گاز', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (27, 'IND-PETRO', 'پتروشیمی', 'پروژه‌های پتروشیمی', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (28, 'IND-MINING', 'معدن', 'استخراج و فرآوری معدن', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (29, 'IND-STEEL', 'فولاد و فلزات', 'پروژه‌های صنایع فولاد و فلزی', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (30, 'IND-CEMENT', 'سیمان', 'پروژه‌های صنایع سیمان', 1, SYSDATE);

-- Telecommunication Activities
INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (31, 'TEL-FIBER', 'فیبر نوری', 'احداث شبکه فیبر نوری', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (32, 'TEL-MOBILE', 'شبکه موبایل', 'احداث دکل و تجهیزات موبایل', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (33, 'TEL-DATA', 'شبکه داده', 'احداث و نگهداری شبکه داده', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (34, 'TEL-SECURITY', 'امنیت و نظارت', 'نصب سیستم‌های امنیتی و دوربین', 1, SYSDATE);

-- Consulting Activities
INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (35, 'CON-DESIGN', 'طراحی', 'خدمات طراحی و نقشه‌کشی', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (36, 'CON-SUPER', 'نظارت', 'نظارت بر اجرای پروژه', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (37, 'CON-MANAGE', 'مدیریت پروژه', 'مدیریت و کنترل پروژه', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (38, 'CON-STUDY', 'مطالعات', 'مطالعات فنی و اقتصادی', 1, SYSDATE);

-- Service Activities
INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (39, 'SRV-MAINT', 'نگهداری', 'خدمات نگهداری و تعمیرات', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (40, 'SRV-CLEAN', 'نظافت', 'خدمات نظافت و بهداشت', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (41, 'SRV-SECURITY', 'نگهبانی', 'خدمات نگهبانی و حفاظت', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (42, 'SRV-TRANS', 'حمل و نقل', 'خدمات حمل و نقل و لجستیک', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (43, 'SRV-CATERING', 'تغذیه', 'خدمات تغذیه و رستوران', 1, SYSDATE);

-- Landscaping Activities
INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (44, 'LAND-GARDEN', 'فضای سبز', 'احداث و نگهداری فضای سبز', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (45, 'LAND-PARK', 'پارک و بوستان', 'احداث پارک و بوستان', 1, SYSDATE);

-- Environmental Activities
INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (46, 'ENV-WASTE', 'مدیریت پسماند', 'جمع‌آوری و بازیافت پسماند', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (47, 'ENV-WATER', 'تصفیه آب', 'تصفیه و پالایش آب', 1, SYSDATE);

-- Demolition Activities
INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (48, 'DEMO-BUILD', 'تخریب ساختمان', 'تخریب و آواربرداری', 1, SYSDATE);

INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (49, 'DEMO-EXCAVATE', 'خاکبرداری', 'خاکبرداری و گودبرداری', 1, SYSDATE);

-- Other Activities
INSERT INTO BASE_CONTRACTOR_ACTIVITY (ID, ACTIVITY_CODE, ACTIVITY_NAME, DESCRIPTION, IS_ACTIVE, CREATED_DATE)
VALUES (50, 'OTHER', 'سایر فعالیت‌ها', 'سایر فعالیت‌های تخصصی', 1, SYSDATE);

COMMIT;
