-- Insert Contractor Categories
-- Main categories for Iranian contractors based on common classification
-- Schema: ID, CATEGORY_CODE (50 chars), CATEGORY_NAME (200 chars), DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE

-- Level 1: Main Categories (no parent)
INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (1, 'BUILD', 'ساختمانی', 'پیمانکاران ساختمانی و عمرانی', NULL, 1, 1, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (2, 'ROAD', 'راهسازی', 'پیمانکاران راه و راهسازی', NULL, 1, 2, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (3, 'WATER', 'آب و فاضلاب', 'پیمانکاران آب و فاضلاب', NULL, 1, 3, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (4, 'POWER', 'برق و انرژی', 'پیمانکاران برق، انرژی و روشنایی', NULL, 1, 4, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (5, 'MECH', 'تاسیسات مکانیکی', 'پیمانکاران تاسیسات مکانیکی', NULL, 1, 5, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (6, 'INDUST', 'صنعتی', 'پیمانکاران صنعتی و تولیدی', NULL, 1, 6, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (7, 'TRANSP', 'حمل و نقل', 'پیمانکاران حمل و نقل و لجستیک', NULL, 1, 7, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (8, 'TELECOM', 'مخابرات و ارتباطات', 'پیمانکاران مخابرات و شبکه', NULL, 1, 8, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (9, 'CONSULT', 'مشاوره', 'شرکت‌های مشاور', NULL, 1, 9, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (10, 'SERVICE', 'خدماتی', 'پیمانکاران خدماتی و پشتیبانی', NULL, 1, 10, SYSDATE);

-- Level 2: Sub-categories for Building (parent: 1)
INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (101, 'BUILD-RES', 'ساختمان مسکونی', 'احداث ساختمان‌های مسکونی', 1, 1, 1, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (102, 'BUILD-COM', 'ساختمان تجاری', 'احداث ساختمان‌های تجاری و اداری', 1, 1, 2, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (103, 'BUILD-IND', 'ساختمان صنعتی', 'احداث سوله و ساختمان‌های صنعتی', 1, 1, 3, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (104, 'BUILD-INFRA', 'زیرساخت', 'زیرساخت‌های عمرانی', 1, 1, 4, SYSDATE);

-- Level 2: Sub-categories for Road (parent: 2)
INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (201, 'ROAD-HIGH', 'بزرگراه', 'احداث و نگهداری بزرگراه', 2, 1, 1, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (202, 'ROAD-CITY', 'راه شهری', 'راه‌سازی شهری و معابر', 2, 1, 2, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (203, 'ROAD-BRIDGE', 'پل و تونل', 'احداث پل و تونل', 2, 1, 3, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (204, 'ROAD-ASPH', 'آسفالت', 'آسفالت و روکش راه', 2, 1, 4, SYSDATE);

-- Level 2: Sub-categories for Water (parent: 3)
INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (301, 'WATER-SUPP', 'تامین آب', 'شبکه تامین و توزیع آب', 3, 1, 1, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (302, 'WATER-WASTE', 'فاضلاب', 'شبکه جمع‌آوری فاضلاب', 3, 1, 2, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (303, 'WATER-TREAT', 'تصفیه', 'تصفیه‌خانه آب و فاضلاب', 3, 1, 3, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (304, 'WATER-DAM', 'سد و مخزن', 'احداث سد و مخازن آب', 3, 1, 4, SYSDATE);

-- Level 2: Sub-categories for Power (parent: 4)
INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (401, 'POWER-GEN', 'تولید برق', 'نیروگاه و تولید برق', 4, 1, 1, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (402, 'POWER-DIST', 'توزیع برق', 'شبکه توزیع و انتقال برق', 4, 1, 2, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (403, 'POWER-RENEW', 'انرژی تجدیدپذیر', 'خورشیدی، بادی و تجدیدپذیر', 4, 1, 3, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (404, 'POWER-LIGHT', 'روشنایی', 'روشنایی شهری و معابر', 4, 1, 4, SYSDATE);

-- Level 2: Sub-categories for Mechanical (parent: 5)
INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (501, 'MECH-HVAC', 'سرمایش و گرمایش', 'سیستم‌های HVAC', 5, 1, 1, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (502, 'MECH-PLUMB', 'لوله‌کشی', 'لوله‌کشی و تاسیسات بهداشتی', 5, 1, 2, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (503, 'MECH-ELEV', 'آسانسور', 'نصب و نگهداری آسانسور', 5, 1, 3, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (504, 'MECH-FIRE', 'اطفاء حریق', 'سیستم‌های اطفاء حریق', 5, 1, 4, SYSDATE);

-- Level 2: Sub-categories for Industrial (parent: 6)
INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (601, 'INDUST-OIL', 'نفت و گاز', 'صنایع نفت، گاز و پتروشیمی', 6, 1, 1, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (602, 'INDUST-MINE', 'معدن', 'استخراج و فرآوری معدن', 6, 1, 2, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (603, 'INDUST-MANUF', 'تولیدی', 'کارخانجات و خطوط تولید', 6, 1, 3, SYSDATE);

INSERT INTO CONTRACTOR_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION, PARENT_CATEGORY_ID, IS_ACTIVE, DISPLAY_ORDER, CREATED_DATE)
VALUES (604, 'INDUST-STEEL', 'فولاد و فلزات', 'صنایع فولاد و فلزی', 6, 1, 4, SYSDATE);

COMMIT;
